{{- if and .Values.oauthService.enabled .Values.oauthService.secret.create (not .Values.oauthService.secret.existingSecret) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "reviewstack-dev.oauthSecretName" . }}
  labels:
    {{- include "reviewstack-dev.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.oauthService.secret.clientIdKey }}: {{ .Values.oauthService.secret.clientId | quote }}
  {{ .Values.oauthService.secret.clientSecretKey }}: {{ .Values.oauthService.secret.clientSecret | quote }}
{{- end }}
