{{- if and .Values.config.enabled .Values.config.createSecret (not .Values.config.existingSecret) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "reviewstack-dev.configSecretName" . }}
  labels:
    {{- include "reviewstack-dev.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.config.secretKey }}: |
    window.REVIEWSTACK_CONFIG = {{ .Values.config.data | toJson }};
{{- end }}
