{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "reviewstack-dev.serviceAccountName" . }}
  labels:
    {{- include "reviewstack-dev.labels" . | nindent 4 }}
{{- end }}
